//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationery_firmBD_DZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product() { }
        public Product(int id,string prod_name,string type, int count, decimal costprice, decimal sellprice)
        {
            this.Id = id;
            this.Product_Name = prod_name;
            this.Type = type;
            this.Count = count;
            this.CostPrice = costprice;
            this.SellPrice = sellprice;
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Type { get; set; }
        public int Count { get; set; }
        public decimal CostPrice { get; set; }
        public decimal SellPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }

       

    }
}
