//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationery_firmBD_DZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public System.DateTime Date_of_sale { get; set; }
        public int Count_sale { get; set; }
        public int Prod_Id { get; set; }
        public int Manager_Id { get; set; }
        public int Firm_buyer_Id { get; set; }
    
        public virtual Firm_buyer Firm_buyer { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Product Product { get; set; }
        public Sales() { }
        public Sales(int id, DateTime date_of_sale, int count_sale, int prod_Id, int manager_Id, int firm_buyer_Id)
        {
            Id = id;
            Date_of_sale = date_of_sale;
            Count_sale = count_sale;
            Prod_Id = prod_Id;
            Manager_Id = manager_Id;
            Firm_buyer_Id = firm_buyer_Id;
            
        }
    }
}
