//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopwithSQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int Id { get; set; }
        public string Book_Name { get; set; }
        public string Book_Author { get; set; }
        public string Genre { get; set; }
        public string Book_publisher { get; set; }
        public System.DateTime Publish_date { get; set; }
        public decimal Price { get; set; }
        public bool Top_today { get; set; }
        public bool Top_of_the_week { get; set; }

        public BookTable() { }
        public BookTable(int id,string b_name,string b_author, string b_genre, string b_publisher,DateTime p_date,decimal b_price,bool top_day,bool top_week)
        {
            Id = id;
            Book_Name = b_name;
            Book_Author = b_author;
            Genre = b_genre;
            Book_publisher = b_publisher;
            Publish_date = p_date;
            Price = b_price;
            Top_today = top_day;
            Top_of_the_week = top_week;
        }
    }
}
